#!/bin/sh

set -e
set -x

command -v rcup >/dev/null || {
  echo "rcm is required: apt install rcm / brew install rcm" >&2
  exit 1
}

cd
mkdir -p git
cd git
rm -rf scriptlets
git clone https://github.com/krlmlr/scriptlets.git
cd scriptlets
make
