#!/bin/sh

set -e
set -x

repo=$(git remote -v | sed -r -n '/^origin.*fetch/ {s/^.*github[.]com.(.*)[.]git .*$/\1/;P}')
toplevel=$(git rev-parse --show-toplevel)

cd "${toplevel}/.git"
wget -e robots=off -m -l 2 -E -k -p -np --cut-dirs=2 --regex-type pcre --accept-regex '^.*/(?:issues(?:|[?]page=.*)|issues/[0-9]*|pull/[0-9]+|pulls(?:|[?]page=.*))$' https://github.com/${repo}/
