#!/bin/bash

set -e

if [ -z "$1" ]; then
  echo "Usage: $0 <target-branch> ..."
  exit 1
fi

GITDIR=$(git rev-parse --show-toplevel)
TMPDIR="${GITDIR}.git.merge"

mkdir "${TMPDIR}"

function cleanup {
  rm -rf "${TMPDIR}"
}
trap cleanup EXIT


SOURCE_BRANCH="$(git branch | sed -n -r '/^\* (.*)$/ {s//\1/;p}')"
[ -n "${SOURCE_BRANCH}" ]

TARGET_BRANCH="$1"
shift

find "${GITDIR}" -mindepth 1 -maxdepth 1 -print0 | xargs -0 cp -r -l -t "${TMPDIR}/"
cd "${TMPDIR}"
echo "Working directory: ${TMPDIR}" 1>&2
git reset HEAD
git checkout .
git clean -f -d -x
git checkout "${TARGET_BRANCH}"
git merge "${SOURCE_BRANCH}" "$@"
git push "${GITDIR}" "${TARGET_BRANCH}"
cd "${GITDIR}"

