#!/bin/bash

set -e

SOURCE_DIR=home

INSTALL_FILES=$(cd ${SOURCE_DIR} && find ./* -type f)

INSTALL_DIR=~

LN_ARGS=("$@")

for f in ${INSTALL_FILES}; do
	target_file=$(echo "${INSTALL_DIR}/$f" | sed 's#dot-#.#g')
	source_file=${PWD}/${SOURCE_DIR}/$f

	if ! [ -h "${target_file}" ] || [ "$(readlink -- "${target_file}")" != "${source_file}" ]; then
		if mkdir -v -p "$(dirname "${target_file}")"; then
			if [[ ! "${target_file}" == */.dummy ]]; then
				ln "${LN_ARGS[@]}" -v -s "${source_file}" "${target_file}" || diff --report-identical-files "${source_file}" "${target_file}" || true
			fi
		else
			echo "Error: can't create $(dirname "${target_file}")"
		fi
	fi
done

if [ -d private ]; then private/install; fi
