#!/bin/sh

DoRun() {
  if $SCRIPT; then
    notify-send -i emblem-default "$0: $SCRIPT"
  else
    exitcode=$?
    notify-send -u critical "$0: $SCRIPT"
    return $exitcode
  fi
}

SCRIPT="$@"
if [ "$SCRIPT" = "" ]; then
  echo "Usage: $0 <command> <parameters...>" >> /dev/stderr
  exit 1
fi

DoRun
