#!/bin/sh

DoRun() {
  if sh -c "$SCRIPT"; then
    notify-send -i emblem-default "$0: $SCRIPT"
  else
    notify-send -u critical "$0: $SCRIPT"
  fi
}

SCRIPT=$*
if [ "$SCRIPT" = "" ]; then
  echo "Usage: $0 <command> <parameters...>" >> /dev/stderr
  exit 1
fi

DoRun

