#!/bin/sh

set -e

RPROJ_FILE="$(find -maxdepth 1 -name '*.Rproj' -print -quit)"
if [ "$RPROJ_FILE" = "" ]; then
  Rscript -e "devtools::use_rstudio()" || echo "Version: 1.0
AutoAppendNewline: Yes
StripTrailingWhitespace: Yes
" > $(basename $PWD).Rproj
fi

rstudio "$(find -maxdepth 1 -name '*.Rproj' -print -quit)" 2> /dev/null 1> /dev/null &
