#!/bin/bash

COMMAND=("$@")
for i in "${COMMAND[@]}"
do
	COMMANDSTRING="${COMMANDSTRING} '"${i//"'"/"'\''"}"'"
done;
COMMANDSTRING="${COMMANDSTRING} 2>&1"

DATA=$(mktemp)
TIME=$(mktemp)

{
	echo "${USER}@${HOSTNAME}:${PWD/$HOME/~}\$ $*" > $TIME
	COMMAND=("$@" "2>&1")
	$(which time) -v $(which sh) -c "$COMMANDSTRING" 2>> $TIME
} | tee /dev/stderr | (if which uuencode; then uuencode $1.log; else cat; fi) > $DATA

head -n 3 $TIME

cat $TIME $DATA | mail -s "$(echo -n $* | head -c 80): $(sed -n '2p' $TIME)" ${USER}

rm $TIME $DATA
